### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'lower'

### ISSUE THREAD

**Issue by dmd** [wtclarke/spec2nii#20]
```
$ spec2nii dicom my-input-file.dcm
Traceback (most recent call last):
  File "/cm/shared/anaconda3/bin/spec2nii", line 10, in <module>
    sys.exit(main())
  File "/cm/shared/anaconda3/lib/python3.9/site-packages/spec2nii/spec2nii.py", line 485, in main
    spec2nii(*args)
  File "/cm/shared/anaconda3/lib/python3.9/site-packages/spec2nii/spec2nii.py", line 247, in __init__
    args.func(args)
  File "/cm/shared/anaconda3/lib/python3.9/site-packages/spec2nii/spec2nii.py", line 466, in anon
    self.imageOut, self.fileoutNames = anon_nifti_mrs(args)
  File "/cm/shared/anaconda3/lib/python3.9/site-packages/spec2nii/anonymise.py", line 27, in anon_nifti_mrs
    nifti_mrs_img = nib.load(args.file)
  File "/cm/shared/anaconda3/lib/python3.9/site-packages/nibabel/loadsave.py", line 47, in load
    is_valid, sniff = image_klass.path_maybe_image(filename, sniff)
  File "/cm/shared/anaconda3/lib/python3.9/site-packages/nibabel/filebasedimages.py", line 499, in path_maybe_image
    froot, ext, trailing = splitext_addext(filename,
  File "/cm/shared/anaconda3/lib/python3.9/site-packages/nibabel/filename_parser.py", line 265, in splitext_addext
    if endswith(filename, ext):
  File "/cm/shared/anaconda3/lib/python3.9/site-packages/nibabel/filename_parser.py", line 223, in _iendswith
    return whole.lower().endswith(end.lower())
AttributeError: 'PosixPath' object has no attribute 'lower'
```

**Comment by wtclarke** [comment]
Hi @dmd , Sorry for the delay in responding.

This looks like an issue with nibabel, possibly a version issue. Could you tell me what version nibabel you are using?

You should be able to get this from `conda list`, or opening python and running:
```
import nibabel as nib
nib.__version__
```
I believe anything higher than 3.0 should handle Pathlib paths.

I'll make sure the version requirements for spec2nii are updated.

Will

**Comment by dmd** [comment]
Thanks, that did the trick.
