### ISSUE TITLE
spec2nii ge Pfile: spec2nii.GE.ge_read_pfile.UnknownPfile: No Pfile mapper for pulse sequence = slaser

### ISSUE THREAD

**Issue by weberam2** [wtclarke/spec2nii#90]
Hi Will,
I couldn't find this error elsewhere, so I hope this is the right place.
I am trying to analyze some GE semi LASER data, but I get an error right away trying to convert the Pfile to Nifti

`spec2nii ge P39424.7`

Gives me this error:

`Traceback (most recent call last):
  File "/home/weberam2/miniconda3/bin/spec2nii", line 8, in <module>
    sys.exit(main())
  File "/home/weberam2/miniconda3/lib/python3.8/site-packages/spec2nii/spec2nii.py", line 521, in main
    spec2nii(*args)
  File "/home/weberam2/miniconda3/lib/python3.8/site-packages/spec2nii/spec2nii.py", line 272, in __init__
    args.func(args)
  File "/home/weberam2/miniconda3/lib/python3.8/site-packages/spec2nii/spec2nii.py", line 473, in ge
    self.imageOut, self.fileoutNames = read_pfile(args.file, args.fileout)
  File "/home/weberam2/miniconda3/lib/python3.8/site-packages/spec2nii/GE/ge_pfile.py", line 66, in read_pfile
    pfile = Pfile(filename)
  File "/home/weberam2/miniconda3/lib/python3.8/site-packages/spec2nii/GE/ge_read_pfile.py", line 133, in __init__
    self.map_data()
  File "/home/weberam2/miniconda3/lib/python3.8/site-packages/spec2nii/GE/ge_read_pfile.py", line 275, in map_data
    mapper = self.get_mapper
  File "/home/weberam2/miniconda3/lib/python3.8/site-packages/spec2nii/GE/ge_read_pfile.py", line 209, in get_mapper
    raise UnknownPfile("No Pfile mapper for pulse sequence = %s" % psd)
spec2nii.GE.ge_read_pfile.UnknownPfile: No Pfile mapper for pulse sequence = slaser
`

I'm happy to send you the Pfile if that helps

Cheers,

Alex W.

**Comment by wtclarke** [comment]
@weberam2 I realised I never got back to you about this. It should have been published back in May/June. I'll close this now, but feel free to reopen (or open a new issues) if there are remaining issues.
